name: ci

on:
  pull_request:
    branches:
      - main
    types:
      - synchronize
      - edited

jobs:
  semantic_pull_request:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: amannn/action-semantic-pull-request@v4

  tests:
    needs: semantic_pull_request
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci
      - run: npm test
