name: CI

on:
  pull_request:
    branches:
      - main
    types:
      - synchronize
      - edited

jobs:
  check_sv:
    name: Check Semantic Version PR
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: amannn/action-semantic-pull-request@v4

  tests:
    name: Run Unit Tests
    needs: check_sv
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
